### ISSUE TITLE
Generic version handling

### ISSUE THREAD

**Issue by Fromell** [samverkansgruppen/vals-schemata#2]
Please add:
- Documentation version handling in levels like, Ex 1.2.3
where first number is major changes and not backward compatible, second is minor, that represent functional changes or extentions but is backward compatible. The third level is used for corrections of typo's or clarifications of existing functionality.
This is typically how ITxPT.org defines their version handling of standards for Public transport.

In MQTT topic stucture the "major" version is represented as 
Ex.
service/itxpt/2/avms/runmonitoring
where "2" is pointing to major version 2.x.y of the avms runmonitoring service (duty login)
The upcoming JSON payload will contain internal version handling of "minor" level and below (x.y)

I propose that this project use the same concept !

**Comment by jschlyter** [comment]
We're not going to change the topics at this point, but I've added a version property to the payload.

**Comment by jschlyter** [comment]
We might be able to change the topic names after all, will follow up shortly.

**Comment by c96mer** [comment]
About the topic names, typo there.. /service/v1/atStop for ex. should be service/v1/atStop
Also, by having major version in the topic, payload's version property will simply contain "0.0" at the moment?

**Comment by jschlyter** [comment]
The topics version property should contain the complete version, as of now `1.0.0`

**Comment by jschlyter** [comment]
@Fromell please confirm this is ok

**Comment by jschlyter** [comment]
ping @Fromell

**Comment by Fromell** [comment]
Next Thursday the ITxPT has a technical review board meeting
The current proposal is:
- use only major version (../itxpt/v2/...)
- In JSON messages use the full version number (2.0.0)
