### ISSUE TITLE
In/out of service indicator

### ISSUE THREAD

**Issue by jschlyter** [samverkansgruppen/vals-schemata#6]
How should the realtime system indicate if the vehicle is in or out of service?

**Comment by jschlyter** [comment]
Topic XXX with message content:

    {'RunState': XXX}

@Fromell?

**Comment by Fromell** [comment]
ITxPT mqtt baserade version av AVMS kommer att bygga på JSON meddelanden baserade på
DtD beskrivningarna i "3.6.4.2.1 Run Monitoring Operation" i S02 ver.2.x.x dokumentet.

Den efterfrågade infon finns i:
"RunState" och "PatternRunType"

samt xml ex. nedan:
`<RunMonitoringDelivery version="1.0">
<MonitoredRunState>
	<RecordedAtTime>2017-07-16T11:43:27</RecordedAtTime>
	<MonitoredBlockRef>9301</MonitoredBlockRef>
	<CurrentRunInfo>
		<RunState>RunToPattern</RunState>
		<PatternRunType>JourneyPattern</PatternRunType>
		<JourneyPatternRef>9308</JourneyPatternRef>
		<VehicleJourneyRef>930110</VehicleJourneyRef>
	</CurrentRunInfo>
	<NextRunInfo>
		<RunState>RunToPattern</RunState>
		<PatternRunType>JourneyPattern</PatternRunType>
		<JourneyPatternRef>9311</JourneyPatternRef>
		<VehicleJourneyRef>930111</VehicleJourneyRef>
	</NextRunInfo>
</MonitoredRunState>
</RunMonitoringDelivery>`

That in JSON will be something like:
`{
	"RunMonitoringDelivery": {
		"MonitoredRunState": {
			"RecordedAtTime": "2017-07-16T11:43:27",
			"MonitoredBlockRef": "9301",
			"CurrentRunInfo": {
				"RunState": "RunToPattern",
				"PatternRunType": "JourneyPattern",
				"JourneyPatternRef": "9308",
				"VehicleJourneyRef": "930110"
                                "VerifiedRunState": "true"
			},
			"NextRunInfo": {
				"RunState": "RunToPattern",
				"PatternRunType": "JourneyPattern",
				"JourneyPatternRef": "9311",
				"VehicleJourneyRef": "930111"
			}
		},
		"_version": "2.0.0"
	}
}`

OBS, utökning med "VerifiedRunState": "true" vilket bekräftar om något Backoffice system har konfirmerat utsättningen.

mqtt topic:
service/itxpt/v2/avms/runmonitoring

[S02v2.0_2017_ITxPT_Onboard_Architecture_Specification.pdf](https://github.com/samverkansgruppen/vals-schemata/files/2397132/S02v2.0_2017_ITxPT_Onboard_Architecture_Specification.pdf)

**Comment by jschlyter** [comment]
Perhaps:

    {
    	"version": "2.0.0",
    	"monitoredRunState": {
    		"recordedAtTime": "2017-07-16T11:43:27",
    		"monitoredBlockRef": "9301",
    		"currentRunInfo": {
    			"runState": "RunToPattern",
    			"patternRunType": "JourneyPattern",
    			"journeyPatternRef": "9308",
    			"vehicleJourneyRef": "930110",
    			"verifiedRunState": "true"
    		},
    		"nextRunInfo": {
    			"runState": "RunToPattern",
    			"patternRunType": "JourneyPattern",
    			"journeyPatternRef": "9311",
    			"vehicleJourneyRef": "930111"
    		}
    	}
    }

**Comment by Fromell** [comment]
Hi,
Yes, by some reason the version was moved to bottom at the translation from
XML => JSON

/Anders


Den ons 19 sep. 2018 kl 21:29 skrev Jakob Schlyter <notifications@github.com

**Comment by Fromell** [comment]
Added "commandPath" that tells modules or systems that are allowed to change the state of the duty login information where to post changes.

```
{
	"version": "2.0.0",
	"commandPath": "service/itxpt/v2/avms/command/login/duty"
	"monitoredRunState": {
		"recordedAtTime": "2017-07-16T11:43:27",
		"monitoredBlockRef": "9301",
		"currentRunInfo": {
			"runState": "RunToPattern",
			"patternRunType": "JourneyPattern",
			"journeyPatternRef": "9308",
			"vehicleJourneyRef": "930110",
			"verifiedRunState": "true"
		},
		"nextRunInfo": {
			"runState": "RunToPattern",
			"patternRunType": "JourneyPattern",
			"journeyPatternRef": "9311",
			"vehicleJourneyRef": "930111"
		}
	}
}
```

**Comment by jschlyter** [comment]
I need a JSON schema for this, is the example above complete?
